config/routes.rb
Rails.application.routes.draw do
  
  get 'homes/home'
  get '/account',to:'users#account'
  get '/profile',to:'users#profile'
  devise_for :users,controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to: "homes#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/',to:'homes#home'
  
  resources :users
  get 'rooms/search',to:'rooms#search'
  get 'rooms/posts',to:'rooms#posts'
  resources :rooms
  resources :reservations
   
 

 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>rt2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header>
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 header-container shadow-sm">
        
          <div class="header-left-container">
              <%= link_to root_path do %>
              <img class="my-0 mr-md-auto font-weight-normal" id="home-logo" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png">
              <% end %>
                <div class="header-search-container mt-3">
                      <div class="header-search-box">
                        <%= form_with url: rooms_search_path,method: :get,local: true do |f| %>
                          <%= f.text_field :area ,placeholder:"エリア検索",class:"header-search-input"%>
                          <% submit_tag %>
                        <% end %>
                        <i class="fas fa-map-marker-alt"></i>
                      </div>

                      <div class="header-search-box">
                        <%= form_with url: rooms_search_path,method: :get,local: true do |f| %>
                          <%= f.text_field :keyword ,placeholder:"キーワード検索",class:"header-search-input"%>
                          <% submit_tag %>
                        <% end %>
                        <i class="fas fa-search "></i>
                      </div>
                  </div>
            </div>

 
            <div class="header-right-container">
              <% if user_signed_in? %>
                <div class="p-2 m-1 text-white header-user-name"><%= current_user.name %></div>


                  <div class="dropdown">
                      <button type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false"><!---CSS icon foto--->
                      <div class="user_header_image nav-item p-2 m-1">
                            <% if current_user.image.attached? %>
                              <%= image_tag current_user.image ,style: "border-radius: 50%",:size => "65x65" %>
                            <%else%>
                              <%= image_tag "upper_body-2.png",style: "border-radius: 50%",:size => "65x65"%>
                            <%end%>
                      </div>
                      </button>

                  
                      <ul class="p-2 mb-0 header-nav-menu dropdown-menu" aria-labelledby="dropdownMenuButton" >
                        <li class="mb-1"><%=link_to "ルーム登録",new_room_path,class: "nav_link dropdown-item",:style=>"color:black;"%></li>
                        <li class="mb-1"><%=link_to "予約済みルーム一覧",reservations_path,class: "nav_link dropdown-item",:style=>"color:black;" %></li>
                        <li class="mb-1"><%=link_to "登録済みルーム一覧",rooms_posts_path,class: "nav_link dropdown-item",:style=>"color:black;"%></li>
                        <li class="mb-1"><%=link_to "設定",account_path,class: "nav_link dropdown-item",:style=>"color:black;"%></li>
                        <li class="mb-1"><%=link_to "ログアウト",destroy_user_session_path,method: :delete,class: "nav_link dropdown-item",:style=>"color:black;"%></li>
                      </ul>
                    </div>






                  <% else %>  
                    <%= link_to"ログイン","/users/sign_in",class:"home-link-user p-2 m-1 btn btn-outline-primary text-white bg-primary"%>
                    <%= link_to"新規登録","/users/sign_up",class:"home-link-user p-2 m-1 btn btn-outline-info text-white bg-info"%>
                <% end %>  
                  
            </div>
      </div>



            <script>
              $('.user_headnav').hide();
              $('.user_header_image').on('click',function(){
                $('.user_headnav').slideToggle();
              })
            </script>
    </header>
              <main>
                <div class="clearfix">
                  <%= notice %>
                  <%= alert %>
                </div>
                <%= yield %>
              </main>


               <footer>
                 <p>©︎ 2020 POTEPAN.INC.</p>
               </footer>
  </body>
</html>